### ISSUE TITLE
Add back buttons to landing pages

### ISSUE THREAD

**Issue by thefridge111** [thefridge111/team7#17]
These back buttons need to allow the user to return to the previous page. AKA: the home page of the app. To reiterate, these back buttons are not merely placeholders but actually functional.

**Comment by thefridge111** [comment]
@jrochefo given the amount of other outstanding issues you have I think we should re-assign this issue to @kschafrick, thoughts?

**Comment by jrochefo** [comment]
@thefridge111  @kschafrick that would take some of the load off me and this relates to the issue he also has i believe.
