### ISSUE TITLE
Encyclopedia backend designed

### ISSUE THREAD

**Issue by thefridge111** [thefridge111/team7#20]
Flow diagram of the encyclopedia created. How the code flow will work, API defined, etc. Become familiar with wikipedia API referenced in this projects wiki. This is how we will import entries for the database. Use JSON format for easier data scraping.

**Comment by jrochefo** [comment]
"Flow diagram of the encyclopedia created. How the code flow will work" everything else invalid.  Not using API not using JSON.

**Comment by jrochefo** [comment]
Push back a week
