### ISSUE TITLE
Create Database 

### ISSUE THREAD

**Issue by thefridge111** [thefridge111/team7#28]
Using the schema created in #21 install/setup the database on the appropriate server. Whether that is a server downstairs in the basement or an app-engine server will be decided. This will include the create table statements.

**Comment by thefridge111** [comment]
https://cloud.google.com/solutions/mobile/how-to-build-mobile-app-with-app-engine-backend-tutorial/

**Comment by jrochefo** [comment]
Have external database need to export and implement with Android Studio sqlite

**Comment by jrochefo** [comment]
@thefridge111 I have no idea what i'm doing with android studio and have tried making a test database on a blank project and still can't manage to get it to work.

http://www.techotopia.com/index.php/An_Android_Studio_SQLite_Database_Tutorial

**Comment by thefridge111** [comment]
http://developer.android.com/training/basics/data-storage/databases.html @jrochefo that lays out how to do it better. Otherwise we can facebook chat or meet up if you need me to give you a hand. Youre basically going to create a class (called a 'model') for each table with the methods(functions) being your interface into the db.

**Comment by jrochefo** [comment]
I'll give it a try

**Comment by jrochefo** [comment]
Switched Database to one table
